# Generated by Django 3.2.4 on 2021-06-20 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.IntegerField()),
                ('trans_on', models.DateTimeField(auto_now_add=True, help_text='Transaction Time')),
            ],
            options={
                'db_table': 'transaction',
            },
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='User Name', max_length=30)),
                ('mobile', models.CharField(db_index=True, help_text='User Mobile', max_length=14)),
                ('email', models.EmailField(help_text='User Email', max_length=40, unique=True)),
                ('password', models.CharField(help_text='User Password', max_length=300)),
                ('address', models.CharField(help_text='User Address', max_length=100)),
                ('balance', models.IntegerField(default=1000, help_text='User Balance')),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.AddIndex(
            model_name='usermodel',
            index=models.Index(fields=['email', 'password'], name='user_email_4f5c7e_idx'),
        ),
        migrations.AddField(
            model_name='transactionmodel',
            name='trans_from',
            field=models.ForeignKey(db_column='trans_from', help_text='Transfer From', on_delete=django.db.models.deletion.CASCADE, related_name='trans_from2', to='faceapp.usermodel'),
        ),
        migrations.AddField(
            model_name='transactionmodel',
            name='trans_to',
            field=models.ForeignKey(db_column='trans_to', help_text='Transfer To', on_delete=django.db.models.deletion.CASCADE, related_name='trans_to2', to='faceapp.usermodel'),
        ),
    ]
